<?
$PERM["import-polzovateley.php"]["*"]="D";
$PERM["import-polzovateley.php"]["7"]="X";
$PERM["/"]["*"]="D";
$PERM["/"]["G1"]="X";
$PERM["personal"]["8"]="W";
$PERM["catalog"]["8"]="W";
$PERM["news"]["8"]="W";
$PERM["about"]["8"]="W";
$PERM["index.php"]["8"]="W";
?>